name: Linting&Testing

on:
    push:
        branches: [master, development]

    # Allows to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    linting:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up NodeJS
              uses: actions/setup-node@v1
              with:
                  node-version: 16.20.2

            - name: Install Node dependencies
              run: yarn install --frozen-lockfile

            - name: Lint Project
              uses: wearerequired/lint-action@v2
              with:
                  eslint: true
                  prettier: true

    check-nuxt-env:
        needs: linting
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install Node dependencies
              run: yarn install --frozen-lockfile

            - name: Build project
              run: yarn run build

            - name: Run Project
              run: yarn run start
              timeout-minutes: 1
