name: Linting&Testing

on:
    push:
        branches: [master]

    # Allows to run this workflow manually from the Actions tab
    workflow_dispatch:

env:
    DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }}

jobs:
    linting:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: 14.17.0

            - name: Gen Package-lock
              run: npm install --package-lock-only

            - name: Install Node dependencies
              run: npm ci

            - name: Lint Project
              uses: wearerequired/lint-action@v1
              with:
                  eslint: true
                  prettier: true

    check-nuxt-env:
        needs: linting
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install Node dependencies
              run: npm ci

            - name: Build project
              run: npm run build

            - name: Run Project
              run: npm run start

    k8s-manifest-testing:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install Datree
              run: curl https://get.datree.io | /bin/bash

            - name: Run Datree's policy check
              run: datree test ./config/manifest.yaml
