name: Testing

on:
    #     push:
    #         branches: [master]

    #     # Allows to run this workflow manually from the Actions tab
    workflow_dispatch:

env:
    DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }}

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            # Get current package.json Version
            - name: Get current package version
              id: package-version
              uses: martinbeentjes/npm-get-version-action@v1.1.0

            - name: Build Docker Image
              id: build-image
              run: docker build -t ${{ secrets.DOCKER_IMAGE }}:${{ steps.package-version.outputs.current-version}} .

            - name: Install Datree
              run: curl https://get.datree.io | /bin/bash

            - name: Run Datree's policy check
              run: datree test ./config/manifest.yaml
